DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tweets CASCADE;
DROP TABLE IF EXISTS wallets CASCADE;
DROP TABLE IF EXISTS shares CASCADE;
DROP TABLE IF EXISTS endpoints CASCADE;
DROP TABLE IF EXISTS user_endpoints CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(30) UNIQUE NOT NULL,
  name VARCHAR(30) NOT NULL,
  password VARCHAR(30) NOT NULL
);

CREATE TABLE tweets (
  id SERIAL PRIMARY KEY NOT NULL,
  tweetdatetime TIMESTAMP DEFAULT NOW(),
  tweet VARCHAR(255) NOT NULL,
  tweetread BOOLEAN,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);


CREATE TABLE wallets (
  id SERIAL PRIMARY KEY NOT NULL,
  balance INTEGER,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE shares (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  value INTEGER,
  user_id INTEGER REFERENCES users(id)
);

CREATE TABLE endpoints (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE user_endpoints (
  id SERIAL PRIMARY KEY NOT NULL,
  endpoint_id INTEGER REFERENCES endpoints(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
