DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tweet CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  nameusername VARCHAR(30) UNIQUE NOT NULL,
  password VARCHAR(30) NOT NULL
);

CREATE TABLE tweet (
  id SERIAL PRIMARY KEY NOT NULL,
  tweetdatetime TIMESTAMP DEFAULT NOW(),
  tweetread BOOLEAN,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
