DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tweets CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(30) UNIQUE NOT NULL,
  password VARCHAR(30) NOT NULL
);

CREATE TABLE tweets (
  id SERIAL PRIMARY KEY NOT NULL,
  tweetdatetime TIMESTAMP DEFAULT NOW(),
  tweet VARCHAR(255) NOT NULL,
  tweetread BOOLEAN,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);


